import jbook from "./images/jbook.png";
import diceroll from "./images/diceroll.png";
import simongame from "./images/simongame.png";
import yelpcamp from "./images/yelpcamp.png";

const projects = [
	{
		title: "YelpCamp",
		description:
			"Imitation of Yelp for Campgrounds. Reviews and recommendations of the best camping sites.",
		image: yelpcamp,
		link: "https://yelpcamp-dandemo.herokuapp.com/"
	},
	{
		title: "JBook",
		description:
			"Interactice coding environment. You can write Javascript, import any module, see it get executed, and write comprehensive documentation using markdown. Run 'npx jsnote-dan serve' in your terminal.",
		image: jbook
	},
	{
		title: "Dice Roll",
		description: "Simple dice roll app to determine a winner between 2 players.",
		image: diceroll,
		link: "https://dannnsoh.github.io/DiceRoll/"
	},
	{
		title: "Simon Game",
		description:
			"Memory skill game inspired by Simon. Requires the player to repeat a series of tones and corresponding colours generated by the game.",
		image: simongame,
		link: "https://dannnsoh.github.io/SimonGame/"
	}
];

export default projects;
